# Generated by Django 3.1.1 on 2020-11-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_auto_20201117_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='messagetext',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
