# Generated by Django 3.1.1 on 2020-11-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_auto_20201117_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='messagetext',
            field=models.CharField(default='Hello', max_length=500),
        ),
    ]
